In [2]:
import numpy as np

arr = np.array([1,2,3,4,5,6])

filter_arr =  arr >= 3

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True  True  True]
[3 4 5 6]


In [3]:
import pandas as pd

mydict = {
    "department":["CS", "CE", "ME", "CM"],
    "person": ["Pathak", "Sujan", "Yug", "Sups"]
}
var = pd.DataFrame(mydict, index=['0','1','2','3'])

print(var)

  department  person
0         CS  Pathak
1         CE   Sujan
2         ME     Yug
3         CM    Sups


In [4]:
import numpy as np

x = np.array([2,3,4])
y = np.array([5,6,7])

z = np.gcd(x,y)
a = np.lcm(x,y)

print(z)
print(a)

[1 3 1]
[10  6 28]
